---
title: "Results Processing"
author: "Xi Chen"
date: "July 15, 2016"
output:
  pdf_document: default
  html_document: default
---

```{r Result, echo=FALSE}
library(RJSONIO)
setwd("/Users/bill/Documents/Git/Mix_Gammas")
Results <- fromJSON("./Result/sim2.json")

# Generates all the conditions ###################################
parameters <- function(){
        conditions <- list()
        # Condition 1
        conditions[["C1"]] <- data.frame(c(2,5),c(3,4),c(0.5,0.5))
        colnames(conditions[["C1"]]) <- c("a", "b", "l")
        # Condition 2
        conditions[["C2"]] <- data.frame(c(2,5),c(3,4),c(0.2,0.8))
        colnames(conditions[["C2"]]) <- c("a", "b", "l")
        # Condition 3
        conditions[["C3"]] <- data.frame(c(1,10),c(1,1),c(0.5,0.5))
        colnames(conditions[["C3"]]) <- c("a", "b", "l")
        # Condition 4
        conditions[["C4"]] <- data.frame(c(1,10),c(1,1),c(0.2,0.8))
        colnames(conditions[["C4"]]) <- c("a", "b", "l")
        # Condition 5
        conditions[["C5"]] <- data.frame(c(2,30),c(3,2),c(0.5,0.5))
        colnames(conditions[["C5"]]) <- c("a", "b", "l")
        # Condition 6
        conditions[["C6"]] <- data.frame(c(2,30),c(3,2),c(0.2,0.8))
        colnames(conditions[["C6"]]) <- c("a", "b", "l")
        # Condition 7
        conditions[["C7"]] <- data.frame(c(2,5,6),c(3,5,7),c(1/3,1/3,1/3))
        colnames(conditions[["C7"]]) <- c("a", "b", "l")
        # Condition 8
        conditions[["C8"]] <- data.frame(c(2,5,6),c(3,5,7),c(0.2,0.3,0.5))
        colnames(conditions[["C8"]]) <- c("a", "b", "l")
        # Condition 9
        conditions[["C9"]] <- data.frame(c(1,20,50),c(2,4,3),c(0.2,0.3,0.5))
        colnames(conditions[["C9"]]) <- c("a", "b", "l")
        # Condition 10
        conditions[["C10"]] <- data.frame(c(1,20,50),c(2,4,3),c(0.2,0.3,0.5))
        colnames(conditions[["C10"]]) <- c("a", "b", "l")
        # Condition 11
        conditions[["C11"]] <- data.frame(c(2,50,180),c(1,2,3),c(0.2,0.3,0.5))
        colnames(conditions[["C11"]]) <- c("a", "b", "l")
        # Condition 12
        conditions[["C12"]] <- data.frame(c(2,50,180),c(1,2,3),c(0.2,0.3,0.5))
        colnames(conditions[["C12"]]) <- c("a", "b", "l")
        return(conditions)
}
conditions <- parameters()
```

```{r Processing, echo=FALSE}
# Processing ########################################################


condition.names <- sapply(seq(1, 12), function(x){paste("C",x,sep = "")})
sample.sizes <- sapply(seq(1, 3), function(x){ paste("S",x,sep = "") })
paras <- c("loglik", "gamma.pars", "lambda")

process.f <- function(para){
        results.proced <- list()
        for(i in condition.names){
                results.proced[[i]] <- list()
                for(j in 1:length(sample.sizes)){
                        results.proced[[i]][[sample.sizes[j]]] <- lapply(Results, function(x){
                                x[[i]][[j]][[para]]
                        })
                }
        }
        return(results.proced)
}  

for(para in paras){
        assign(para, process.f(para))
}




# Calculation ########################################################
# calculate the MSEs from the true parameter value as well as the mean and standard deviation of your parameter estimates; 
# i.e., the MC standard deviation of your 5000 estimates will provide an estimate of the standard errors for each parameter.

stat.loglik <- lapply(loglik, function(x){
        lapply(x, function(y){
                dat <- unlist(y)
                stats <- cbind(mean(dat), sd(dat))
                colnames(stats) <- c("mean", "sd")
                return(stats)
        })
})

stat.lambda <- lapply(1:length(lambda), function(c){
        l <- conditions[[c]]$l
        x <- lambda[[c]]
        lapply(x, function(y){
                dat <- t(as.data.frame(y))
                row.names(dat) <- NULL
                mu <- apply(dat, 2, function(i){mean(i)})
                sd <- apply(dat, 2, function(i){sd(i)})
                mse <- sapply(1:length(l), function(i){
                        mean(sum((dat[,i] - l[i]) ^ 2))
                })
                stats <- cbind(mu, sd, mse)
                colnames(stats) <- c("mean", "sd", "mse")
                return(stats)
        })
})

stat.alpha <- lapply(1:length(gamma.pars), function(c){
        a <- conditions[[c]]$a
        x <- gamma.pars[[c]]
        lapply(x, function(y){
                dat <- t(as.data.frame(y[[1]]))
                row.names(dat) <- NULL
                mu <- apply(dat, 2, function(i){mean(i)})
                sd <- apply(dat, 2, function(i){sd(i)})
                mse <- sapply(1:length(a), function(i){
                        mean(sum((dat[,i] - a[i]) ^ 2))
                })
                stats <- cbind(mu, sd, mse)
                colnames(stats) <- c("mean", "sd", "mse")
                return(stats)
        })
})

stat.beta <- lapply(1:length(gamma.pars), function(c){
        b <- conditions[[c]]$b
        x <- gamma.pars[[c]]
        lapply(x, function(y){
                dat <- t(as.data.frame(y[[2]]))
                row.names(dat) <- NULL
                mu <- apply(dat, 2, function(i){mean(i)})
                sd <- apply(dat, 2, function(i){sd(i)})
                mse <- sapply(1:length(b), function(i){
                        mean(sum((dat[,i] - b[i]) ^ 2))
                })
                stats <- cbind(mu, sd, mse)
                colnames(stats) <- c("mean", "sd", "mse")
                return(stats)
        })
})
```

1. Log-likelyhood Statistics
```{r, echo=FALSE}
print(stat.loglik)
```
2. Lambda Statistics
```{r, echo=FALSE}
print(stat.lambda)
```
3. Alpha Statistics
```{r, echo=FALSE}
print(stat.alpha)
```
4. Beta Statistics
```{r, echo=FALSE}
print(stat.beta)
```

